### ISSUE TITLE
Add 'Custom Development' to Noticed

### ISSUE THREAD

**Issue by MackenzieK** [Shopify/plus-partnerships#12]
Noticed requested the additional of Custom Development to their listed services on their directory profile. I can confirm they offer custom development as a service so it should be listed.

**Comment by chrisrwilliams** [comment]
@MackenzieK fantastic thank you - will get that updated. Adam also send some info over this weekend, can you make sure everything looks good below before we update:

**Location**
New York, United States

**Partner Card**
Noticed is a New York and Los Angeles-based digital commerce, optimization and marketing agency. We accelerate growth for enterprise B2B, and direct-to-consumer eCommerce brands in the fashion, lifestyle and beauty industries through enterprise cloud technology, data-driven design, and strategic marketing campaigns. 

**About Text**
Noticed is a New York and Los Angeles-based digital commerce, optimization and marketing agency. We accelerate growth for enterprise B2B, and direct-to-consumer eCommerce brands in the fashion, lifestyle and beauty industries through enterprise cloud technology, data-driven design, and strategic marketing campaigns. 
 
As one of the world's leading Shopify Plus Partners with a global client portfolio and offices in Philadelphia, New York, Los Angeles and Bangalore, we are trusted by retailers of all sizes—from small businesses to enterprise-level brands.
 
At the core, we are driven by flawless design experiences, cutting-edge technology, revenue acceleration and maximum profitability for our customers’ growth. We believe in delivering constantly evolving solutions that drive continuous lifetime value to our customers. 

**Services**

- Design
- Development
- Strategy
- Systems Integrations
- Marketing 
- Conversion Optimization

**Comment by chrisrwilliams** [comment]
@MackenzieK You can let Noticed know the changes are now live: https://www.shopify.ca/plus/partners/noticed
