### ISSUE TITLE
Directory Edits for Brand Online

### ISSUE THREAD

**Issue by joelmbronkowski** [Shopify/plus-partnerships#14]
1) Please edit the city name for Brand Online to 'Neuilly-sur-Seine'

2) Please edit the url from brand-online.com to brandonline.agency

3) Change logo to new logo for directory is [here](https://drive.google.com/a/shopify.com/file/d/0B3q22owicm1Ba3J5a3NrclV1Z2ZoUl9aQVMxbTZyQksxQ1JN/view?usp=sharing) 

@chrisrwilliams

**Comment by chrisrwilliams** [comment]
@joelmbronkowski submitted! will follow up once live

**Comment by chrisrwilliams** [comment]
@joelmbronkowski updates now live https://www.shopify.ca/plus/partners/brand-online
