### ISSUE TITLE
Overview page - Technology Partner definition suggestion

### ISSUE THREAD

**Issue by philvanstone** [Shopify/plus-partnerships#3]
@chrisrwilliams On http://4872c017.ngrok.io/partners I'm wondering if it will be clear enough to merchants why they would choose to the tech partner category. 

Maybe even just by adjusting the definition to something like:

- Tech partners - from "Technology providers that extend the value of Shopify Plus to our merchants." to "Partners that extend the value of Shopify Plus through specialized and highly-integrated technologies." or something that suggests merchants should look in that directory for additional features.

**Comment by chrisrwilliams** [comment]
Thanks @philvanstone! Great suggestion. Final copy by marketing reads as "Ecommerce providers and integrations that extend the value of Shopify Plus to our merchants."
