### ISSUE TITLE
Monumental's logo is wrong

### ISSUE THREAD

**Issue by philvanstone** [Shopify/plus-partnerships#5]
Hey @chrisrwilliams, this request is urgent in Monumental's eyes: the logo we're showing on the directory (and that's linked in the google sheet) is wrong. The proper one can be found here:  http://thisismonumental.com/images/shopify-experts/MM-shopify-plus-thumb.png

**Comment by chrisrwilliams** [comment]
Thank you @philvanstone! Will get this updated ASAP. Once we push it live, I'll reach out to you so you can let Monumental know about the fix

**Comment by chrisrwilliams** [comment]
@philvanstone Can you reach out to Monumental about getting a vector copy of their logo?

**Comment by philvanstone** [comment]
Thanks, @chrisrwilliams. An svg can be found here: https://drive.google.com/file/d/0BxTz1Q_vBMS0ZWExaWxLOGJzVkU/view?usp=sharing

Also, can you please add a paragraph break so that "We have been Shopify Experts since 2013–and built with Shopify even before that. We're not the type to sneak out the morning after a project launch. We value relationships with our clients that last, so that we can grow together." is in its own paragraph.

**Comment by chrisrwilliams** [comment]
Perfect, thank you @philvanstone! Updated. Will ping you when it's live
