### ISSUE TITLE
Change URL link for Plus Solution Partner Ryan Foster

### ISSUE THREAD

**Issue by aliciacornell** [Shopify/plus-partnerships#6]
Please change the link for his listing from shopifyplus.ryanfosterdesign.com (which gives an error) to ryanfosterdesign.com. 

https://www.shopify.ca/plus/partners/ryanfosterdesign

**Comment by chrisrwilliams** [comment]
@aliciacornell Request has been submitted, will follow back when it's live so you can let Ryan know. Thank you!

**Comment by chrisrwilliams** [comment]
@aliciacornell RYD now links to right domain

https://www.shopify.com/plus/partners/ryanfosterdesign
