### ISSUE TITLE
Move Stream Commerce to Agency Partner

### ISSUE THREAD

**Issue by aliciacornell** [Shopify/plus-partnerships#7]
Stream commerce is currently listed as a Solutions Partner, but they offer all services as defined by an agency partner, and should be categorized as such. 

Please move them to the Agency Partner listings. Thanks! @chrisrwilliams 

https://www.shopify.ca/plus/partners/stream-commerce

**Comment by chrisrwilliams** [comment]
@aliciacornell Request has been submitted, will follow back when it's live. Thank you!

**Comment by chrisrwilliams** [comment]
Stream is now classified as an Agency partner: https://www.shopify.com/plus/partners/stream-commerce
