### ISSUE TITLE
Update logo for DIFF Agency

### ISSUE THREAD

**Issue by aliciacornell** [Shopify/plus-partnerships#8]
Please update to the correct logo for DIFF agency. https://www.shopify.ca/plus/partners/diff
![diff_logo-ps-whitemark_v0 3](https://user-images.githubusercontent.com/29069233/27041293-954b0bac-4f61-11e7-8047-e62ae68d6b5c.png)

![diff_logo-ps-whitemark_v0 3](https://user-images.githubusercontent.com/29069233/27041286-8d570856-4f61-11e7-85d6-e8018770490f.png)

**Comment by chrisrwilliams** [comment]
@aliciacornell Perfect thank you! Will follow up once it's live.

**Comment by chrisrwilliams** [comment]
https://www.shopify.com/plus/partners/diff

@aliciacornell Diff's new logo is up! Cheers.
