### ISSUE TITLE
Update long copy for Stream Commerce listing

### ISSUE THREAD

**Issue by aliciacornell** [Shopify/plus-partnerships#9]
Please update the long copy text on the Stream Commerce Directory listing to be the below: (there were errors in their original submission)

https://www.shopify.ca/plus/partners/stream-commerce
--------------
Stream Commerce is a full-service digital commerce boutique agency providing a comprehensive suite of end-to-end ecommerce solutions.
 
We are your digital retail brand growth partner. Helping you navigate the future of retail.
 
Led by passionate expert enterprise ecommerce operators, we uniquely understand your day-to-day challenges. Learn and benefit from our enterprise ecommerce experience in scaling profitable sales and delivering seamless omni-channel world class customer experiences.
 
Flexible and responsive, we build a plan with you and uniquely work together to make it happen. We design and develop mobile, desktop & tablet optimized Shopify Plus & Shopify e-commerce online stores; related commerce technology, systems integration and app strategy, selection & implementation. As your digital merchant & digital marketing partner, we build your online store, and work with you post launch to grow your business.
 
Whether you are building from scratch, upgrading from Shopify to Shopify Plus or migrating from Magento, Demandware or another platform, no Shopify Plus project is too big or small for our dedicated team. We have experience in B2C and B2B ecommerce projects. Our ongoing managed services, including: outsourced site operations, digital performance growth marketing and optimization consulting, help set us apart.
 
Through our sister company, Think Logistics, we run the Kiva robotic system to support your warehousing and ecommerce fulfillment needs.
 
We are a "one-stop" partner or work on a solution-by-solution basis:
 
• Strategic ecommerce consulting
• Shopify Plus & Shopify responsive ecommerce stores and related commerce technology
• Ongoing Managed Service: Digital performance growth marketing & Optimization Consulting
• Ecommerce Logistics & Retail Fulfillment
• Back-office support and administration

**Comment by chrisrwilliams** [comment]
@aliciacornell text updated!
